name: Deploy User Management App

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/user-management-app/**'
      - '.github/workflows/deploy-user-management.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/user-management-app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        cd frontend/user-management-app
        npm ci
        
    - name: Build application
      run: |
        cd frontend/user-management-app
        npm run build
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: frontend/user-management-app/build
        destination_dir: user-management
