name: Deploy All Micro-Frontends

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install root dependencies
      run: npm ci
      
    - name: Install all app dependencies
      run: |
        cd frontend/container && npm ci
        cd ../user-management-app && npm ci
        cd ../data-grid-app && npm ci
        cd ../analytics-app && npm ci
        cd ../settings-app && npm ci
      
    - name: Build all applications
      run: |
        cd frontend/container && npm run build
        cd ../user-management-app && npm run build
        cd ../data-grid-app && npm run build
        cd ../analytics-app && npm run build
        cd ../settings-app && npm run build
      
    - name: Test all applications
      run: |
        cd frontend/container && npm test -- --coverage --watchAll=false
        cd ../user-management-app && npm test -- --coverage --watchAll=false
        cd ../data-grid-app && npm test -- --coverage --watchAll=false
        cd ../analytics-app && npm test -- --coverage --watchAll=false
        cd ../settings-app && npm test -- --coverage --watchAll=false
      
  deploy-container:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        cd frontend/container
        npm ci
        
    - name: Build application
      run: |
        cd frontend/container
        npm run build
        
    - name: Deploy Container to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: frontend/container/build
        destination_dir: container
        
  deploy-micro-frontends:
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: 
          - { name: 'user-management-app', destination: 'user-management' }
          - { name: 'data-grid-app', destination: 'data-grid' }
          - { name: 'analytics-app', destination: 'analytics' }
          - { name: 'settings-app', destination: 'settings' }
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        cd frontend/${{ matrix.app.name }}
        npm ci
        
    - name: Build application
      run: |
        cd frontend/${{ matrix.app.name }}
        npm run build
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: frontend/${{ matrix.app.name }}/build
        destination_dir: ${{ matrix.app.destination }}
