name: Deploy Container App

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/container/**'
      - '.github/workflows/deploy-container.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/container/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'frontend/container/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd frontend/container
        npm ci
        
    - name: Build application
      run: |
        cd frontend/container
        npm run build
        
    - name: Deploy to Vercel
      uses: vercel/action@v1
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_CONTAINER }}
        working-directory: frontend/container
        vercel-args: '--prod'
