name: Deploy Container App

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/container/**'
      - '.github/workflows/deploy-container.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/container/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        cd frontend/container
        npm ci
        
    - name: Build application
      run: |
        cd frontend/container
        npm run build
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: frontend/container/build
        destination_dir: container
        cname: micro-frontend-container.github.io
